### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by Zongwei97** [rkyuca/medvt#2]
Hi,
Thanks for your great work.
Will the training code be released?
Thanks

**Comment by rkyuca** [comment]
Hi Zongwei, 
Thank you for your kind words. I expect to release the training code soon. I need to clean up the code and then upload. I hope to do so by next week. 
Thanks.

**Comment by rkyuca** [comment]
Hi Zongwei,
The training codes are uploaded now. 
Thanks.
